PROJECT=Next186_SoC
MANIFEST=manifest.rtl
BOARDS_ALTERA = "de2 chameleon64 chameleon64v2 mist c3board"

all:
	make -f ../Scripts/standard.mak PROJECT=$(PROJECT) BOARDS_ALTERA=$(BOARDS_ALTERA)

clean:
	make -f ../Scripts/standard.mak PROJECT=$(PROJECT) BOARDS_ALTERA=$(BOARDS_ALTERA) clean

